version: '2'
services:
  web:
    image: cvugrinec/java-webapp-redisdemo:2.0
    depends_on:
      - redis
    ports:
      - 8080:8080
    links:
      - redis
    expose:
      - 8080

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    expose:
      - 6379
